// Popular and real-world departments
const List<String> popularDepartments = [
  'Computer Science',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Electrical Engineering',
  'Electronics Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Environmental Engineering',
  'Industrial Engineering',
  'Mechatronics',
  'Robotics',
  'Telecommunications',
  'Chemical Engineering',
  'Business Administration', 'Finance', 'Marketing', 'Economics', 'Accounting',
  'Physics',
  'Mathematics',
  'Statistics',
  'Biology',
  'Chemistry',
  'Biotechnology',
  'Psychology',
  'Sociology',
  'Political Science',
  'History',
  'Philosophy',
  'Linguistics',
  'Art',
  'Design',
  'Architecture',
  'Urban Planning',
  'Education',
  'Law',
  'Medicine',
  'Public Health', 'Nursing', 'Dentistry', 'Pharmacy', 'Veterinary Science',
  'Agricultural Science', 'Forestry', 'Food Science', 'Geology', 'Geography',
  'International Relations', 'Development Studies', 'Sustainable Development',
  'Gender Studies', 'Media Studies', 'Communication', 'Tourism', 'Hospitality',
  'Sports Science', 'Physical Education', 'Library Science', 'Marine Science',
  // AIT-specific
  'Information and Communication Technologies',
  'Industrial Systems Engineering',
  'Mechatronics',
  'Remote Sensing and Geographic Information Systems',
  'Water Engineering and Management',
  'Environmental Engineering and Management',
  'Urban Environmental Management',
  'Sustainable Energy Transition',
  'Disaster Preparedness, Mitigation and Management',
  'Development and Sustainability',
  'Agricultural Systems and Engineering',
  'Aquaculture and Aquatic Resources Management',
  'Food Engineering and Bioprocess Technology',
  'Gender and Development Studies',
  'Natural Resources Management',
  'Regional and Rural Development Planning',
  'Urban Water Engineering and Management',
];
