// Popular and real-world universities (with focus on Thailand and AIT)
const List<String> popularUniversities = [
  // Thailand
  'Asian Institute of Technology (AIT)',
  'Chulalongkorn University',
  'Mahidol University',
  'Thammasat University',
  'King Mongkut’s University of Technology Thonburi (KMUTT)',
  'King Mongkut’s Institute of Technology Ladkrabang (KMITL)',
  'King Mongkut’s University of Technology North Bangkok (KMUTNB)',
  'Kasetsart University',
  'Chiang Mai University',
  'Prince of Songkla University',
  'Suranaree University of Technology',
  'Khon Kaen University',
  'Burapha University',
  'Srinakharinwirot University',
  'Naresuan University',
  'Silpakorn University',
  'Mae Fah Luang University',
  'Walailak University',
  'Rajamangala University of Technology',
  // International
  'Harvard University',
  'MIT',
  'Stanford University',
  'University of Oxford',
  'University of Cambridge',
  'NUS',
  'NTU',
  'IIT Bombay',
  'IIT Delhi',
  'Kathmandu University',
  'Tribhuvan University',
  'Monash University',
  'University of Melbourne',
  'University of Toronto',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Tokyo',
  'Seoul National University',
  'Chulalongkorn University',
  'AIT',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of Michigan',
  'University of Washington',
  'University of British Columbia',
  'ETH Zurich',
  'Tsinghua University',
  'Peking University',
  'University of Hong Kong',
  'University of Sydney',
  'University of Queensland',
  'University of New South Wales',
  'University of Auckland',
];
